---
title: "Welcome to DATA606!"
author: "Jason Bryer"
date: 2018-08-27
categories: ["R"]
tags: ["Annoucement"]
---

Welcome to DATA606! My name is Dr. Jason Bryer and I will be your instructor for this semester. In addition to teaching this course, I am an Executive Director at [Excelsior College](http://excelsior.edu) where I am currently working on a Department of Education grant to develop a Diagnostic Assessment and Achievement of College Skills (see [www.DAACS.net](http://www.daacs.net) for more information). Our first meeting will be on Wednesday, September 5th. Couple of important notes as you get started:

* The course syllabus is on Github here: [data606.net](http://data606.net) I will post all course materials there. Blackboard will be used primarily for submitting assignments.
* Introduce yourself in the Getting Acquainted forum on Blackboard.
* Once you go through the syllabus, try starting Lab 0 as soon as you can. This will require you to install R and RStudioand will help get you get acquainted with R.
* The best way to reach me is by email at jason.bryer@gmail.com. If you would prefer to talk on the phone or setup a GoToMeeting session, it is best to suggest some times by email first.
* Our meetups will be on Wednesday from 8pm to 9pm.
* I am looking forward to getting to know everyone and a fantastic semester! Good luck!

<iframe width="560" height="315" src="https://www.youtube.com/embed/i2DM7nqb1rA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

